### ISSUE TITLE
Data container is superfluous

### ISSUE THREAD

**Issue by foxfabi** [foxfabi/docker-webdev#1]
Based on this [answers](https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql?answertab=votes#tab-top), persistent data should use [data-volumes](https://docs.docker.com/storage/volumes/)

```
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
```
